#Enable Enemies Swarming You
enablesiege = true
#Enable Increased Enemy Presence
incenemies = true
#Enable Creeper Jockies
isjockies = true
#Charged Creepers Spawn Naturally
ischargedcreepers = true
#Allow Bloodlusting Enemies
isbloodlusting = true
#Give Zombies Pickaxes and Weapons?
iszombiepickaxes = true
#Give Zombies Armor?
iszombiearmor = true
#Give Skeletons Armor?
isskeletonarmor = true
#Allow Zombies to Lay TNT?
iszombietnt = true
#Chance of zombies placing TNT each tick if in distance.
zombietntchance = 0.25
#How close zombies need to be to player to allow setting TNT.
zombietntdistance = 2
#Allow Zombies To Destroy Blocks? SETTING IS DEPRECATED AND WILL BE REMOVED IN FUTURE RELEASE. Please set mobGriefing server game rule instead.
iszombiegriefing = true
#Allow Zombies To Place Blocks? DEPRECATED - REPLACED BY mobGriefing game rule. Will be removed in future.
iszombiebuilding = true
#Allow Spiders to Shoot Webs?
isspidershootwebs = true
#Can Creepers Breach Walls?
iscreeperbreaching = true
#Do entities bounce when they touch water? Default = true.
isoceansurfing = true
#Allow Sleeping?
allowsleep = false
#Allow Monster Infighting?
allowmonsterinfighting = false
#Allow Zombies and Piglins to light flammable things on fire?
zombieslightfires = true
#Allow Super Skeletons to Spawn in the Game?
allowsuperskeletons = true
#Creeper Jockey Chance Out of 100
jockeychance = 1
#Chance Entity Duplicate on Spawn (Out of 100)
dupechance = 10
#Chance of Creepers Spawning Charged Out of 100
chargedchance = 1
#Chance of Entities Spawning Bloodlusted Out of 100
angryentitychance = 10
#Distance at Which Creepers Will Breach if Blocked (in Blocks)
breachingdist = 64
#Creepers Will Explode if This Close to Player (in Blocks)
creeperexplodedist = 6
#Distance At Which Creepers Breech the Ground (in Blocks)
creepersbreechgrounddist = 6
#Ticks Until Blocked Creeper Explodes (in Game Ticks)
obstructedcreeperexpticks = 60
#Nuclear Creeper Explosion Radius (Default vanilla is 3
nuclearcreeperexplosionradius = 10
#How long (in ticks) Nuclear Creeper is lit before it blows up
nuclearcreeperfuse = 120
#Chance of Nuclear Creeper out of 100
chancenuclearcreeper = 0.25
#Chance of Zombies Recieving Special Item or Pickaxe Out of 100
pickaxechance = 20
#Chance of Zombies Lighting Flammable Items on Fire Per Tick Out of 100
zombiefirechance = 1.0
#Chance of More Powerful Skeleton Spawning
superskeletonchance = 1.0
#Cooloff time for entities breaking blocks in ticks
entitydigdelay = 5
#Cooloff time for entities placing blocks in ticks
entitybuilddelay = 5
#If entity is within this distance for X and Z, it'll start digging to player
entitydigdist = 32
#Above Ground Monster Attack Distance (in Blocks)
grounddist = 96
#Below Ground Monster Attack Distance (in Blocks)
cavedist = 48
#Chance out of 100 for spider shooting webs each tick. Default = 0.5
spiderwebchance = 0.5
#Distance at which spider can shoot a web at player. Default = 2 blocks
spiderwebdist = 2
#Maximum Duplicated Enemies. Recommend Min. 1, Max. 4.
maxdupes = 3

